spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mariadb://doribottle-database.c92a4l3bvio6.ap-northeast-2.rds.amazonaws.com/doribottle_dev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MariaDBDialect
  data:
    redis:
      host: redis-dev
      port: 6379
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

logging.level:
  org.hibernate.SQL: debug

app:
  web:
    base-url: https://www.doribottle-id.co.kr
    admin-base-url: https://www.admin.doribottle-id.co.kr
  auth:
    jwt:
      base64-secret: ${JWT_SECRET}
      expired-ms: 3600000 # 1hour
      pre-auth-expired-ms: 300000 # 5minute
      system-expired-ms: 3153600000000 # 100year
    refresh-jwt:
      expired-ms: 1209600000 # 2weeks
  ncloud:
    base-url: https://sens.apigw.ntruss.com
    access-key: ${NCLOUD_ACCESS_KEY}
    secret-key: ${NCLOUD_SECRET_KEY}
    notification:
      sms:
        service-path: /sms/v2/services
        service-id: ${NCLOUD_SMS_ID}
        calling-number: ${NCLOUD_SMS_CALLING_NUMBER}
  tosspayments:
    base-url: https://api.tosspayments.com/
    secret-key: ${TOSS_PAYMENTS_SECRET_KEY}
  aws:
    sqs:
      queue-name: point-save-queue.fifo
    s3:
      bucket-name: doribottle-asset
  slack:
    webhook-url: ${SLACK_WEBHOOK_URL}
  schedule:
    enabled: true

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true