spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/doribottle-h2-local
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

jwt:
  secret: ${JWT_SECRET}
  expiredMs: 3600000 # 1hour
