spring:
  datasource:
    url: jdbc:mariadb://doribottle-database.c92a4l3bvio6.ap-northeast-2.rds.amazonaws.com/doribottle_dev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}

logging.level:
  org.hibernate.SQL: debug

app:
  auth:
    jwt:
      secret: ${JWT_SECRET}
      expiredMs: 3600000 # 1hour
      preAuthExpiredMs: 300000 # 5minute
    refreshToken:
      expiredMs: 1209600000 # 2weeks
  toast:
    sms:
      url: https://api-sms.cloud.toast.com/
      appKey: ${TOAST_APP_KEY}
      secretKey: ${TOAST_SECRET_KEY}
      sendNo: ${TOAST_SEND_NO}
  aws:
    sqs:
      queueName: PointSaveEventQueue.fifo